### PR TITLE
fixed all changes on slack "random" channel

### PR DESCRIPTION
**Pull request by christinetu**
- changed google link on FAQ

- fixed footer email 
Screen Shot 2019-04-29 at 9 56 45 PM

- changed padding in about us
image

- added "Home" to navbar in mobile view
image

### CODE REVIEW

**Comment by alecluna** [comment]
looks good

**Comment by alecluna** [comment]
@christinetu  I messed up in the services PR i made today, can you squeeze in a quick fix for this 💯 
Screen Shot 2019-04-29 at 10 39 49 PM

**Comment by chrisdont** [comment]
> @christinetu I messed up in the services PR i made today, can you squeeze in a quick fix for this 💯
> Screen Shot 2019-04-29 at 10 39 49 PM



> @christinetu I messed up in the services PR i made today, can you squeeze in a quick fix for this 💯
> Screen Shot 2019-04-29 at 10 39 49 PM

Should we just do one Request an Estimate button at the bottom? They all just navigate to Estimate and I don't think we need 3 unless it prepopulates the Service input on the form

**Comment by alecluna** [comment]
@chrisdont @christinetu  yeah i'm down for the one estimate button

**Pull request merged**
